name: Test Management UI with Selenium
on:
  push:
    branches:
    - oidc-integration-github-action
jobs:
  make-test-runner-imager:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          curl rabbimq:15672/api/overview
    services:
      rabbitmq:
        image: pivotalrabbitmq/rabbitmq:69a4159f3482e5212d364f499b2ca2e05bede0ca-otp-min
