name: Test Management UI with Selenium
on:
  push:
    branches:
    - oidc-integration-github-action
jobs:
  make-test-runner-imager:
    runs-on: ubuntu-latest
    steps:
      - name: Build test runner image
        uses: docker/build-push-action@v3
        with:
          file: {context}/deps/rabbitmq_management/selenium/Dockerfile-with-tests
          push: false
          tags: mocha-test
          target: test
  run-tests:
    runs-on: ubuntu-latest
    needs: make-test-runner-imager
    steps:
      - name: List tests
        run: |
          docker images | grep mocha-test
