name: Test Management UI with Selenium
on:
  push:
    branches:
    - oidc-integration-github-action
jobs:
  make-test-runner-imager:
    runs-on: ubuntu-latest
    container: curlimages/curl
    services:
      rabbitmq:
        image: pivotalrabbitmq/rabbitmq:69a4159f3482e5212d364f499b2ca2e05bede0ca-otp-min
    steps:
    - uses: actions/checkout@v2
    - name: reach rabbitmq
      run: |
          ls .
          curl -u guest:guest http://rabbitmq:15672/api/overview
