name: Test Management UI with Selenium
on:
  push:
    branches:
    - oidc-integration
jobs:
  Demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List tests
        run: |
          ls ${{ github.workspace }}/deps/rabbitmq_management/selenium
