name: Test Management UI with Selenium
on:
  push:
    branches:
    - oidc-integration-github-action
jobs:
  selenimum:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: localhost:5000/mocha-test:latest
      - name: run tests
        uses: localhost:5000/mocha-test:latest

####
# We need to run these as docker images:
#  UAA
#  RabbitMQ
#  Selenium Tests (maybe these ones could run in the host machine)
#  Selenium Hub (which runs the browser in silent mode)

# The workflow is more or less like this:
# job:build-rabbitmq-image  -> job:build-test-runner-image -> job:run-tests

# job:build-rabbitmq-image : Ideally, we do not want to push it. can we do that in github actions?
#
# job:run-tests : It runs within a container and it uses these services:
#  - rabbitmq
#  - UAA
#  - selenium-hub
# and it has this step which uses the image test-runner built by the job build-test-runner-image
