name: Test Management UI with Selenium
on:
  push:
    branches:
    - oidc-integration
jobs:
  checkout-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
  run-selenimum-test:
    runs-on: ubuntu-latest
    needs: checkout-tests
    steps:
      - name: List tests
        run: |
          ls ${{ github.workspace }}
