name: Test Management UI with Selenium
on:
  push:
    branches:
    - oidc-integration-github-action
jobs:
  make-test-runner-imager:
    runs-on: ubuntu-latest
    container: node:14.15.4
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        ls
        cd deps/rabbitmq_management/selenium
        npm install
    - name: run
      run: |
        cd deps/rabbitmq_management/selenium
       ./node_modules/.bin/mocha --recursive --trace-warnings --timeout 35000 test/oauth/with-uaa
